# -*- coding: utf-8 -*-
"""Churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9cs2j52WtF8DFSfXT3klHa6hmm7Mx0f
"""

# Install if needed:
# pip install tensorflow scikit-learn pandas

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


# Small business dataset
data = pd.DataFrame({
    "Tenure": [2, 24, 12, 3, 36, 5, 48, 8],
    "MonthlySpend": [150, 80, 95, 160, 70, 140, 60, 170],
    "SupportCalls": [6, 1, 2, 7, 0, 5, 1, 6],
    "ContractType": [1, 0, 0, 1, 0, 1, 0, 1],
    "Churn": [1, 0, 0, 1, 0, 1, 0, 1]
})

data


# Small business dataset
data = pd.DataFrame({
    "Tenure": [2, 24, 12, 3, 36, 5, 48, 8],
    "MonthlySpend": [150, 80, 95, 160, 70, 140, 60, 170],
    "SupportCalls": [6, 1, 2, 7, 0, 5, 1, 6],
    "ContractType": [1, 0, 0, 1, 0, 1, 0, 1],
    "Churn": [1, 0, 0, 1, 0, 1, 0, 1]
})

print("Input Data", data)

#step 4
X = data[["Tenure", "MonthlySpend", "SupportCalls", "ContractType"]]
y = data["Churn"]

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

# Scale (important for neural networks)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



#step 5
model = Sequential([
    Dense(6, activation='relu', input_dim=4),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train, y_train, epochs=100, verbose=0)


#step 6
loss, accuracy = model.evaluate(X_test, y_test)
print("Model Accuracy:", round(accuracy, 2))


#Step 7
# Example new customers
new_customers = pd.DataFrame({
    "Tenure": [2, 30],
    "MonthlySpend": [155, 75],
    "SupportCalls": [10, 1],
    "ContractType": [1, 0]
})

# Scale
new_scaled = scaler.transform(new_customers)

# Predict
predictions = model.predict(new_scaled)

for i, prob in enumerate(predictions):
    print(f"Customer {i+1} Churn Probability: {prob[0]:.2f}")