# -*- coding: utf-8 -*-
"""FraudDetectionNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPJNNKIXdJvfhfbN1foO3Iilh5LPH3Oo
"""

# Step 1: Import libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Step 2: Create sample data (UPDATED)
import pandas as pd

data = pd.read_csv("/content/sample_data/fraud_detection_data.csv")

X = data[["Amount", "TimeGap", "LocationChange", "IsInternational"]]
y = data["Fraud"]

# Step 3: Split features and target
X = data[["Amount", "TimeGap", "LocationChange", "IsInternational"]]
y = data["Fraud"]

# Step 4: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Step 5: Build Neural Network (UPDATED input_dim)
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))  # Updated input_dim
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Step 6: Compile Model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Step 7: Train Model
model.fit(X_train, y_train, epochs=50, batch_size=2, verbose=1)

# Step 8: Evaluate Model
loss, accuracy = model.evaluate(X_test, y_test)
print("Accuracy:", accuracy)

# Step 9: Predict New Transaction (UPDATED input)
new_data = np.array([[1000, 1, 1, 1]])  # High risk: international + high amount
prediction = model.predict(new_data)

print("Fraud Probability:", prediction[0][0])
print("Fraud Prediction:", 1 if prediction[0][0] > 0.5 else 0)

